version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
